builddir := "./build"

test:
    meson test -C {{builddir}}

format:
    clang-format -i $(find . -name "**.hpp") $(find . -name "**.cpp")
    
build:
    meson compile -C {{builddir}}

setup-debug:
    meson setup {{builddir}} --buildtype=debug -Db_lundef=false -Db_sanitize=address,undefined --reconfigure

setup-release:
    meson setup {{builddir}} --buildtype=release --reconfigure
